version: 1.2

workflows:
  - name: mimosca-wdl
    subclass: WDL
    primaryDescriptorPath: /mimosca.wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  - name: permute_mimosca-wdl
    subclass: WDL
    primaryDescriptorPath: /permute_mimosca.wdl
    authors: 
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org

  