version: 1.2

workflows:
  - name: mimosca-wdl
    subclass: WDL
    primaryDescriptorPath: /mimosca.wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  - name: permute_mimosca-wdl
    subclass: WDL
    primaryDescriptorPath: /permute_mimosca.wdl
    authors: 
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  - name: similarity_matrix-wdl
    subclass: WDL
    primaryDescriptorPath: /similarity_matrix.wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  - name: combine_mimosca_permuted_coeffs-wdl
    subclass: WDL
    primaryDescriptorPath: /combine_mimosca_permuted_coeffs.wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org

  